name: CI Workflow
on: push


jobs:

#   clone:
#     name: Clone
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup SSH
#         uses: MrSquaare/ssh-setup-action@v1
#         with:
#             host: github.com
#             private-key: ${{ secrets.PRIV_KEY }}

#       - name: Clone repository
#         run: git clone git@github.com:akankshar05/wht.git

#       - name: cd to wht
#         run: |
#           cd wht
#           pwd


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
