# name: CI Workflow
# on: push


# jobs:

# #   clone:
#     name: Clone
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup SSH
#         uses: MrSquaare/ssh-setup-action@v1
#         with:
#             host: github.com
#             private-key: ${{ secrets.PRIV_KEY }}

#       - name: Clone repository
#         run: git clone git@github.com:akankshar05/wht.git

#       - name: cd to wht
#         run: |
#           cd wht
#           pwd


name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install  # Adjust this based on your project setup

      - name: Build
        run: npm run build  # Adjust this based on your project setup

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Adjust this based on your project setup
