name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
            host: github.com
            private-key: ${{ secrets.PRIV_KEY }}

      # - name: Clone repository
      #   run: git clone git@github.com:akankshar05/_gh_pages.git
      - name: Clone repository
        run: git clone git@github.com:akankshar05/nested_folders.git
      - name: cd nested_folders
        run: |
          cd nested_folders
          ls -a
      - name: add siteconfig.yaml
        run: |
          cd ./../../..
          touch siteconfig.yaml
          pwd
          echo "1"
          echo '${{ secrets.SF_CRED }}' > siteconfig.yaml
          echo "2"
          cat siteconfig.yaml
      - name: create dir
        run: |
          mkdir _gh_pages

      - name: copy files
        run: |
          cp -r ${{ github.workspace }}/nested_folders/* ${{ github.workspace }}/_gh_pages
          cd _gh_pages
          ls -a

      - name: clone the gh-thing 
        run: |
          git clone -b gh-pages git@github.com:akankshar05/check_ci.git gh-pages
          cp -r ${{ github.workspace }}/gh-pages/* ${{ github.workspace }}/_gh_pages
      # - name: cd _gh_pages
      #   run: |
      #     cd _gh_pages
      #     touch index.html
      #     cp performance_report.html index.html 
      #     ls -a
      #     cat index.html

       
      - name: nojekyll
        if: ${{ github.event_name == 'push' }}
        run: |
          touch _gh_pages/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: _gh_pages/
          force_orphan: true




