# name: Build and Deploy
# on: [push]
# permissions:
#   contents: write
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup SSH
#         uses: MrSquaare/ssh-setup-action@v1
#         with:
#             host: github.com
#             private-key: ${{ secrets.PRIV_KEY }}

#       - name: Clone repository
#         run: git clone git@github.com:akankshar05/wht.git
#       - name: cd _gh_pages
#         run: |
#           cd wht
#           ls -a
#       - name: create dir
#         run: |
#           mkdir _gh_pages

#       - name: copy files
#         run: |
#           cp -r ${{ github.workspace }}/wht/samples/profiles-performace-report/output/dev/reports/perf*/* ${{ github.workspace }}/_gh_pages
#           cd _gh_pages
#           ls -a
    
#       - name: nojekyll
#         if: ${{ github.event_name == 'push' }}
#         run: |
#           touch _gh_pages/.nojekyll
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         if: ${{ github.event_name == 'push' }}
#         with:
#           publish_branch: gh-pages
#           github_token: ${{ secrets.GH_TOKEN }}
#           publish_dir: _gh_pages/
#           force_orphan: true
# # name: Update GitHub Pages

# # on:
# #   push:
# #     branches:
# #       - main  # Change this to your main branch name

# # jobs:
# #   update-gh-pages:
# #     runs-on: ubuntu-latest
    
# #     steps:
# #     - name: Checkout Repository
# #       uses: actions/checkout@v2

# #     - name: Set up Node.js
# #       uses: actions/setup-node@v3
# #       with:
# #         node-version: '14'

# #     - name: Install Dependencies
# #       run: |
# #         npm install  # Replace with your build commands if you have any

# #     - name: Build and Deploy
# #       run: |
# #         # Replace the build and deploy commands with your specific ones
# #         npm run build  # Replace with your build command
# #         mv your_generated_files docs  # Change to the output directory of your build

# #     - name: Store Previous Version
# #       run: |
# #         timestamp=$(date +"%Y%m%d_%H%M%S")
# #         mv docs previous_pages/$timestamp

# #     - name: Deploy to GitHub Pages
# #       uses: peaceiris/actions-gh-pages@v3
# #       with:
# #         github_token: ${{ secrets.GITHUB_TOKEN }}
# #         publish_dir: ./docs  # Change to your output directory

